name = "BeneathBeyondGame"
uuid = "c777f136-f7dc-5b0b-946e-35c9c44a8c36"
repo = "https://github.com/kalmarek/BeneathBeyondGame.jl"
version = "0.0.1"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
AlphaZero = "8ed9eb0b-7496-408d-8c8b-2119aeea02cd"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"

[compat]
AbstractAlgebra = "0.10.0, 0.11.0"
AlphaZero = "0.3"
julia = "^1.4.0"
